samples/python/agents/a2a_mcp/src/a2a_mcp/agents/orchestrator_agent.py
samples/python/agents/a2a_mcp/src/a2a_mcp/common/prompts.py

fix: Orchestrator agent to respond to task agent queries when possible.

---

samples/python/agents/a2a_mcp/src/a2a_mcp/common/agent_executor.py
samples/python/agents/ag2/__main__.py
samples/python/agents/ag2/agent_executor.py
samples/python/agents/crewai/agent_executor.py
samples/python/agents/google_adk/agent_executor.py
samples/python/agents/headless_agent_auth/agent_executor.py
samples/python/agents/langgraph/agent_executor.py
samples/python/agents/llama_index_file_chat/agent_executor.py
samples/python/agents/marvin/__main__.py
samples/python/agents/marvin/agent_executor.py
samples/python/agents/mindsdb/agent_executor.py
samples/python/agents/semantickernel/__main__.py
samples/python/agents/semantickernel/agent_executor.py

- Removes usages of overrides as the newer implementation doesn't override a base implementation
- Removes unused imports

fix: clean up imports

---

samples/python/agents/a2a_telemetry/README.md
samples/python/agents/a2a_telemetry/__main__.py
samples/python/agents/a2a_telemetry/agent_executor.py
samples/python/agents/a2a_telemetry/docker-compose.yaml
samples/python/agents/a2a_telemetry/pyproject.toml

feat: A2A Tracing: Demonstrate tracing in A2A SDK via a QnA Agent with Jaeger and Grafana

---

samples/python/requirements.txt

Fixes [#709](https://github.com/google-a2a/A2A/issues/709) 🦕

fix: removed unsupported version from python example requirements.txt

---

demo/ui/uv.lock
samples/python/agents/analytics/README.md
samples/python/agents/analytics/__main__.py

(NOT CODE CHANGES)
Syntax fix in ReadMe which caused it to not render perfectly 
Verbiage change in card content

minor fixes to ReadMe syntax and card content

---

samples/python/agents/airbnb_planner_multiagent/pyproject.toml

@holtskinner  Sorry, right before the merge of my previous pr https://github.com/google-a2a/a2a-samples/pull/103 there was a commit made to main that introduced a bad change. Although youy  were able to do the merge cleanly in the github UI, it broke the pyproject.toml configuration (since the airbnb_planner_multiagent is a member of the overally uv project, it has a more general version requirement list). 

feat: fix pyproject.toml of airbnb_multiagent from merge

---

samples/python/agents/a2a_mcp/src/a2a_mcp/common/agent_executor.py
samples/python/agents/a2a_telemetry/agent_executor.py
samples/python/agents/azureaifoundry_sdk/azurefoundryagent/foundry_agent_executor.py
samples/python/agents/birthday_planner_adk/birthday_planner/adk_agent_executor.py
samples/python/agents/birthday_planner_adk/calendar_agent/adk_agent_executor.py
samples/python/agents/google_adk/agent_executor.py
samples/python/agents/langgraph/app/agent_executor.py
samples/python/agents/llama_index_file_chat/agent_executor.py
samples/python/agents/mindsdb/agent_executor.py
samples/python/agents/veo_video_gen/agent_executor.py

- Modified the code to handle the TaskUpdater functions that became async in Python a2a SDK version 0.2.6.
- Fixed some incorrect TaskUpdater function calls.

fix: updates for a2a-sdk 0.2.6

---

.github/workflows/lint.yml
noxfile.py

Use noxfile to check that all files that were touched in the PR are correctly formatted.
The whole repo has many files that don't comply with the ruff format rules in .ruff.toml so we may also want to run 
`ruff check . --fix` and `ruff format .` to get everything back in-line with the format requirements

ci: add lint github action

---

samples/python/hosts/cli/__main__.py

fix: add missing imports for cli

---

README.md

docs: Update README.md with link to a2a-inspector

---

samples/python/agents/adk_cloud_run/.dockerignore
samples/python/agents/adk_cloud_run/Dockerfile
samples/python/agents/adk_cloud_run/README.md
samples/python/agents/adk_cloud_run/__init__.py
samples/python/agents/adk_cloud_run/__main__.py
samples/python/agents/adk_cloud_run/agent.py
samples/python/agents/adk_cloud_run/agent_executor.py
samples/python/agents/adk_cloud_run/pyproject.toml

Re-do of https://github.com/a2aproject/a2a-samples/pull/215 to keep ADK_Facts as it was

feat: Add Cloud Run Deployable A2A Agent

---

samples/python/agents/helloworld/pyproject.toml
samples/python/agents/helloworld/uv.lock

chore: upgrade helloworld to latest sdk version

---

samples/multi_language/python_and_java_multiagent/README.md
samples/multi_language/python_and_java_multiagent/weather_agent/pom.xml

fix: Update the groupId for the A2A Java SDK for the first release

---

samples/python/agents/langgraph/.vscode/launch.json
samples/python/agents/langgraph/app/__main__.py
samples/python/agents/langgraph/app/test_client.py
samples/python/agents/langgraph/pyproject.toml
samples/python/agents/langgraph/uv.lock

chore: update currency agent to 0.2.16

---

samples/python/agents/helloworld/.vscode/launch.json
samples/python/agents/helloworld/__main__.py
samples/python/agents/helloworld/pyproject.toml
samples/python/agents/helloworld/test_client.py
samples/python/agents/helloworld/uv.lock

chore: upgrade helloworld agent to 0.2.16

---

samples/python/agents/adk_cloud_run/pyproject.toml

Deployment was failing due to litellm missing in the dependency list

fix(sample): Add litellm to the dependencies

---

samples/python/agents/semantickernel/.vscode/launch.json
samples/python/agents/semantickernel/__main__.py
samples/python/agents/semantickernel/pyproject.toml
samples/python/agents/semantickernel/uv.lock
samples/python/pyproject.toml

chore: SK example upgrade to 0.3 and make it standalone

---

samples/python/agents/dice_agent_grpc/README.md
samples/python/agents/dice_agent_grpc/__main__.py
samples/python/agents/dice_agent_grpc/test_client.py

chore: Add agent_card support for grpc example

---

extensions/traceability/v1/spec.md
samples/python/extensions/traceability/src/traceability_ext/__init__.py
samples/python/hosts/a2a_multiagent_host/README.md
samples/python/hosts/a2a_multiagent_host/__main__.py
samples/python/hosts/a2a_multiagent_host/host_agent_executor.py
samples/python/hosts/a2a_multiagent_host/uv.lock
samples/python/pyproject.toml
samples/python/uv.lock

feat: traceability extension - more follow up changes - docs update, agent card

---

samples/python/agents/adk_facts/README.md

It took me some time to figure why it did not pick up the vertex ai configuration :)

Region is set via `GOOGLE_CLOUD_LOCATION` env variable
